# Generated by Django 3.1.2 on 2020-10-26 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avellino', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='password',
            new_name='pass_word',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user_name',
        ),
    ]
