# Generated by Django 3.1.2 on 2020-10-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avellino', '0002_auto_20201026_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pass_word',
            new_name='password',
        ),
    ]
