# Generated by Django 3.1.2 on 2020-10-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avellino', '0005_auto_20201029_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
